# DESCRIPTION: GitLab CI/CD for libRetro (NOT FOR GitLab-proper)

##############################################################################
################################# BOILERPLATE ################################
##############################################################################

# Core definitions
.core-defs:
  variables:
    CORENAME: mame2015

.core-defs-cdi2015:
  variables:
    CORENAME: cdi2015
    SUBTARGET: cdi

# Inclusion templates, required for the build to work
include:
  ################################## DESKTOPS ################################
  # Windows 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/windows-x64-mingw.yml'
    
  # Windows 32-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/windows-i686-mingw.yml'
    
  # Linux 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/linux-x64.yml'

  # Linux 32-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/linux-i686.yml'

  # Linux 64-bit (ARM)
  - project: 'libretro-infrastructure/ci-templates'
    file: '/linux-aarch64.yml'

  #################################### MISC ##################################
  # webOS 32-bit (LGTV)
  - project: 'libretro-infrastructure/ci-templates'
    file: '/webos-make.yml'

# Stages for building
stages:
  - build-prepare
  - build-shared

##############################################################################
#################################### STAGES ##################################
##############################################################################
#

##############
## mame2015 ##
##############

################################### DESKTOPS #################################
# Windows 64-bit
libretro-build-windows-x64:
  extends:
    - .libretro-windows-x64-mingw-make-default
    - .core-defs
  variables:
    CC:    ${CXX}
    CC_AS: ${CC}

# Windows 32-bit
libretro-build-windows-i686:
  extends:
    - .libretro-windows-i686-mingw-make-default
    - .core-defs
  variables:
    CC:    ${CXX}
    CC_AS: ${CC}

# Linux 64-bit
libretro-build-linux-x64:
  extends:
    - .libretro-linux-x64-make-default
    - .core-defs

# Linux 32-bit
libretro-build-linux-i686:
  extends:
    - .libretro-linux-i686-make-default
    - .core-defs

# Linux 64-bit (ARM)
libretro-build-linux-aarch64:
  extends:
    - .libretro-linux-aarch64-make-default
    - .core-defs

#############
## cdi2015 ##
#############

################################### DESKTOPS #################################
# Windows 64-bit
libretro-build-windows-x64-cdi2015:
  extends:
    - .libretro-windows-x64-mingw-make-default
    - .core-defs-cdi2015
  variables:
    CC:    ${CXX}
    CC_AS: ${CC}
    
# Windows 32-bit
libretro-build-windows-i686-cdi2015:
  extends:
    - .libretro-windows-i686-mingw-make-default
    - .core-defs-cdi2015
  variables:
    CC:    ${CXX}
    CC_AS: ${CC}
    
# Linux 64-bit
libretro-build-linux-x64-cdi2015:
  extends:
    - .libretro-linux-x64-make-default
    - .core-defs-cdi2015
    
# Linux 32-bit
libretro-build-linux-i686-cdi2015:
  extends:
    - .libretro-linux-i686-make-default
    - .core-defs-cdi2015

# Linux 64-bit (ARM)
libretro-build-linux-aarch64-cdi2015:
  extends:
    - .libretro-linux-aarch64-make-default
    - .core-defs-cdi2015

#################################### MISC ##################################
# webOS 32-bit
libretro-build-webos-armv7a:
  extends:
    - .libretro-webos-armv7a-make-default
    - .core-defs-cdi2015
